config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'

  get 'home/about' => 'homes#about'

  get '/search', to: 'searches#search'

  resources :users, except: [:new] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books, except: [:new] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy


  validates :title, presence: true
  validates :body, presence: true,length: { maximum:200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]

  attachment :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum:50 }

  def already_favorited?(book)
    self.favorites.exists?(book_id: book.id)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])

  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @content = current_user.book_comments.new(book_comment_params)
    @content.book_id = @book.id
    if @content.save
      render :book_comments
    else
      @user = @book.user
      @book_comment = BookComment.new
      render "error"
    end
  end

  def destroy
    BookComment.find_by(id: params[:id]).destroy
    flash.now[:alert] = '投稿を削除しました'
    @book = Book.find(params[:book_id])
    render :book_comments
  end


  private
  def book_comment_params
    params.require(:book_comment).permit(:content)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def show
     @book = Book.find(params[:id])
     @user = @book.user
     @newbook = Book.new
     @book_comment = BookComment.new
     @content = @book
     @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id!=current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),  notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    @favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @book.id)
    @favorite.destroy

  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    @records = search_for(@model, @content, @method)
    @users = @records
    @books = @records
  end

  private

  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward_match'
        User.where("name LIKE?", "#{content}%")
      elsif method == 'backward_match'
        User.where("name LIKE?", "%#{content}")
      else
        User.where('name LIKE ?', '%'+content+'%')
      end


    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def show
     @user = User.find(params[:id])
     @books = @user.books
     @newbook = Book.new
     @book = Book.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book_comments.html.erb
<div>
  <p>コメント件数：<%= book.book_comments.count %></p>
  <table class="table">
  <% book.book_comments.each do |book_comment| %>
  <tr>
  <th><%= attachment_image_tag  @user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %></th>
    <th><%= book_comment.user.name %></th>
    <th><%= book_comment.content %></th>
    <% if book_comment.user == current_user %>
    <div>
      <th><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: 'btn btn-sm btn-danger' %></th>
    </div>
    <% end %>
  <% end %>
  </tr>
  </table>
</div>

app/views/book_comments/_comment_form.html.erb
<div>
<%= form_with(model:[book, @book_comment]) do |f| %>
  <div class="content-error"_<%= @book.id %> >
  <% if content.errors.any? %>
    <h3 class="text-danger"><%= content.errors.count %>error prohibited this obj from being saved:</h3>
    <% content.errors.full_messages.each do |message| %>
      <ul><li class="text-danger"><%= message %></li></ul>
    <% end %>
  <% end %>
  </div>

  <%= f.text_area :content, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit '送信', :class=>'btn btn-success btn-md' %>
<% end %>
</div>

app/views/book_comments/book_comments.js.erb
$(".contents_area_<%= @book.id %>").html("<%= j(render 'book_comments/book_comments', book: @book, content: @content) %>");
$("textarea").val('');

app/views/book_comments/error.js.erb
$(".content-error_<%= @book.id %>").html("<%= j(render 'book_comments/book_comments', book: @book, content: @content) %>");

app/views/books/_userinfo.html.erb
      <h2>User info</h2>
        <%= attachment_image_tag  user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr>
              <th>name</th>
              <th><%= user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= user.introduction %></th>
            </tr>
            <tr>

              <th>follows</th>
              <th><%= link_to user.followings.count, user_followings_path(user) %></th>
            </tr>
            <tr>
              <th>followers</th>
              <th><%= link_to user.followers.count, user_followers_path(user) %></th>

            </tr>
            <tr>
              <% unless user == current_user %>
                <% if current_user.following?(user) %>
                  <%= link_to user_relationships_path(user.id), method: :delete do %>
                    <button class="btn btn-danger">フォロー解除</button>
                  <% end %>
                <% else %>
                  <%= link_to user_relationships_path(user.id), method: :post do %>
                    <button class="btn btn-primary">フォローする</button>
                  <% end %>
                <% end %>
              <% end %>
            </tr>
          </tbody>
       </table>

      <div class="row">
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block", method: :get do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book, local:true do |f| %>
      <div class="form-group">
        <lable for="book_title">Title</lable></br>
        <%= f.text_field :title %>
      </div>
      <div class="form-group">
        <lable for="book_opinion">Opinion</lable></br>
        <%= f.text_area :body %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', :class=>'btn btn-success btn-md' %>
      </div>
      <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
        <h3 class="text-danger"><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <% @book.errors.full_messages.each do |message| %>
          <ul><li class="text-danger"><%= message %></li></ul>
        <% end %>
      <% end %>
      <%= form_with model:@book, local:true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, name:'book[title]', value:@book.title, class: "form-control book_title" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinipn</label>
        <%= f.text_area :body, name:'book[body]', value:@book.body, class: "form-control book_body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-sm btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <h3 class="text-danger"><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
    <ul><li class="text-danger"><%= message %></li></ul>
  <% end %>
<% end %>
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo',book: @book, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td><%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              </td>
                 <% end %>
              <td><%= link_to book.title,book_path(book.id) %></td>
              <td><%= book.body %></td>

              <th class="favorites_buttons_<%= book.id %>">
              <%= render "favorites/favorites", book: book %>
              </th>

              <th>
                 <p><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
              </th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo', book: @newbook, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody></tbody>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td><%=link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body %></td>

              <th class="favorites_buttons_<%= @book.id %>">
              <%= render "favorites/favorites", book: @book %>

              </th>
              <% if @user.id == current_user.id %>
                <th><%= link_to "Edit", edit_book_path(@book.id), class:'btn btn-sm btn-success' %></th>
                <th><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか?", class: 'btn btn-sm btn-danger'%> </th>
              <% end %>
            </tr>
        </tbody>
      </table>

      <div class="new-content">
        <%= render 'book_comments/comment_form', book: @book, content: @content %>
      </div>

      <div class="contents_area_<%= @book.id %>">
        <%= render 'book_comments/book_comments', book: @book %>
      </div>


    </div>
  </div>
</div>

app/views/favorites/_favorites.html.erb
<% if current_user.already_favorited?(book) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
<%= book.favorites.count %>

app/views/favorites/create.js.erb
$(".favorites_buttons_<%= @book.id %>").html("<%= j(render 'favorites/favorites', book: @book) %>");

app/views/favorites/destroy.js.erb
$(".favorites_buttons_<%= @book.id %>").html("<%= j(render 'favorites/favorites', book: @book) %>");

app/views/relationships/followers.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWING</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if current_user.following?(user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                <% if user != current_user %>
                  <% if current_user.following?(user) %>
                    <%=link_to user_relationships_path(user), method: :delete do %>
                      <button type="button" class="btn btn btn-danger">フォロー解除</button>
                    <% end %>
                  <% else %>
                    <%=link_to user_relationships_path(user), method: :post do %>
                      <button type="button" class="btn btn btn-primary">フォロー</button>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div id="error_explanation">
        <% if @user.errors.any? %>
          <h3 class="text-danger"><%= @user.errors.count %> error prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <ul><li class="text-danger"><%= message %></li></ul>
            <% end %>
          </ul>
        <% end %>
      </div>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name",class:"form-control name"%>
        </div>

        <div class="form-group">
          <label for="user_name">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "Image",class:"form-control-file user_image" %>
        </div>


        <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"Introduction",class:"form-control introduction"%>
        </div>

        <div class="form-group">
          <%= f.submit "Update User",class:"btn btn-secondary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo',book: @book, user: @user %>
    </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %></td>
              <td><%= user.name %></td>
              <th>follows</th>
              <th><%= link_to user.followings.count, user_followings_path(user) %></th>
              <th>followers</th>
              <th><%= link_to user.followers.count, user_followers_path(user) %></th>
              <th>
              <% unless user == current_user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー解除", user_relationships_path(user.id), method: :delete  %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post  %>
                <% end %>
              <% end %>
              </th>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/userinfo',book: @newbook, user: @user %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <table class="table">
         <thead>
           <th></th>
           <th>Title</th>
           <th>Opinion</th>
           <th colspan="3"></th>
         </thead>
         <tbody>
         <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg", size: '40x40' %><br>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <th><%= book.body %></th>
            <th>コメント件数：<%= book.book_comments.count %></th>
            <th>

            </th>
          </tr>
          <% end %>
          </tbody>
        </table>
     </div>
  </div>
</div>